# Generated by Django 3.1.2 on 2020-11-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StuffTracker', '0002_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StuffTracker.myuser'),
            preserve_default=False,
        ),
    ]
